import java.io.File;
import javax.swing.JFileChooser;
/**
 * The FileMenuHandler class manages the file selection process using JFileChooser.
 */
public class FileMenuHandler{
    /**
     * Opens a file chooser dialog to select a file.
     * 
     * @param dir The directory to start the file chooser from
     * @return The absolute path of the selected file
     */
    public String populate(File dir){
        String file_path="";
        
        // Create a new file chooser, sets the selection mode so it can access
        // both files and directories. This allows us to maneuver through directories
        // to get to the target file. Then we check if the user has selected a file or 
        // directory by setting the value returned by filechooser.showOpenDialog(null)  
        // to the int option variable and comparing that to the approve option from JFileChooser. 
        // If that is true, we will set the file_path to the absolute path of the selected file 
        // and then we return the file_path. 
        JFileChooser fileChooser = new JFileChooser(); 
        fileChooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        int option = fileChooser.showOpenDialog(null);
        if (option == JFileChooser.APPROVE_OPTION) {
            file_path=fileChooser.getSelectedFile().getAbsolutePath();
        }    
        return file_path;
    }
    /**
     * Gets the absolute path of the selected file or directory.
     * 
     * @param dir The directory to start the file chooser from
     * @return The absolute path of the selected file
     */
    public String getP(File dir){
        // returns the value generated by calling the populate method passing in the parameter dir, 
        // i.e the starting directory. 
        return populate(dir);
    }
};        